config/routes.rb
Rails.application.routes.draw do


  post '/items' => 'items#cart', as: 'add_cart'
  get '/items' => 'items#index', as: 'items'
  get '/items/:category' => 'items#show'

  get '/carts' => 'carts#index', as: 'carts'
  get '/carts/:id' => 'carts#show' , as: 'cart'
  patch '/carts/:id' => 'carts#update'
  delete '/carts/:id' => 'carts#destroy', as: 'delete_cart'


  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show' , as: 'order'
  patch '/orders/:id' => 'orders#update'
  delete '/orders/:id' => 'orders#destroy'
  post '/submit' => 'orders#submit', as: "submit"


  get '/orders/:id/items' => 'items#show' , as: 'order_items'
  delete '/orders/:id/items/:item_id' => 'items#destroy', as: 'order_item_delete'

  root "mains#index"
  get '/kitchen' => 'mains#kitchen'
  get '/table' => 'mains#table', as: "table"
  get '/getorders' => 'mains#orders'
  post '/assigntable' => 'mains#assign', as: "assign"
  get '/releasetable' => 'mains#release', as: "release"
  get '/completeorders' => 'mains#complete'
  post '/destroyalltables' => 'mains#destroy', as: "destroyall"
  delete '/deletetable' => 'tables#destroy', as: "deletetable"

  devise_for :staffs
  resources :tables

  get '/reports' => 'reports#index', as: 'reports'
  get '/sales/:id' => 'sales#show' , as: 'sale'

  get '/notifications' => 'tables#notifications'
  get '/addnotifications' => 'tables#addnotification'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  # belongs_to :order
  validates :item_quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :orders
  # has_many :carts


  # has_many :items_orders
  # has_many :orders, through: :items_orders

  # has_and_belongs_to_many :orders

end

app/models/items_order.rb
class ItemsOrder < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/notification.rb
class Notification < ApplicationRecord
end

# Notification.where('created_at >= :ten_seconds_ago', :ten_seconds_ago => Time.now - 10.seconds)

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :items_orders
  has_many :items, through: :items_orders
  
  # has_and_belongs_to_many :items
  # belongs_to :table
  # belongs_to :sale
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  # belongs_to :table
  has_many :orders
  # belongs_to :report
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/table.rb
class Table < ApplicationRecord
  # belongs_to :sale
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout "items"
  def index
    @carts = Cart.where(:table_id => session[:table]).order(:id)

  end

  def show
    @table = Table.find(session[:table])
    @purchases = Purchase.all
  end

  def update
    puts "add to cart"
    p params
    # p request.query_string
    puts params[:cart][:item_quantity]
      @cart = Cart.find(params[:id])

      @cart.update(:item_quantity => (params[:cart][:item_quantity].to_i))
    puts "finish update"

    # redirect_to carts_path
    redirect_back fallback_location: carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])

    @cart.destroy

    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:table_id, :item_id, :item_quantity)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout "items"

  def index
    @items = Item.all
  end

  def new
  end

  def create
    @item = Item.new(item_params)

    @item.save
    redirect_to @item
  end

  def cart

    if Cart.where(table_id:cart_params[:table_id],item_id:cart_params[:item_id]).empty?
      @cart = Cart.new(cart_params)
      @cart.save
    else
      @cart = Cart.find_by(table_id:cart_params[:table_id],item_id:cart_params[:item_id])
      @cart.item_quantity += cart_params[:item_quantity].to_i
      @cart.save
    end
    flash[:alert] = "#{@cart.item.name} has been successfully added to cart"
    redirect_back fallback_location: items_path

  end

  def show
    puts params.inspect
    if params.has_key?(:category)
      if(params[:category] == "drinks" )
          @items = Item.where(:category => 'drinks')
      elsif (params[:category] == "starter" )
          @items = Item.where(:category => 'starter')
      elsif (params[:category] == "mains" )
          @items = Item.where(:category => 'mains')
      elsif (params[:category] == "desserts" )
          @items = Item.where(:category => 'desserts')
      elsif (params[:category] == "sides" )
          @items = Item.where(:category => 'sides')
      end
    else
      @item = Item.find(params[:id])
    end
  end

  def destroy
      p "DELETINGGGGG"
      p params
      # p params[:format]


      @order = Order.find(params[:id])
      # # p "-------------------------"

      # item = @order.items.find(params[:format])
      # item = @order.items.find(:item_id)

      item = @order.items.find(params[:item_id])
      # item.order_items.delete(order_item_id)


      if item
          @order.items.delete(item)
      end

      redirect_to orders_path

    end
private
  def item_params
    params.require(:item).permit(:name, :category, :price, :picture)
  end

  def cart_params
    params.require(:cart).permit(:table_id, :item_id, :item_quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/carts/index.html.erb
<!-- Shows all items in cart -->

<% allitem = 0 %>

<main class="page-content">
    <div class="container-fluid">


      <div class="row">
        <div class="col-12">
          <h3>Your Cart</h3>
        </div>
      </div>

      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">Item</th>
          <th scope="col">Unit Price</th>
          <th scope="col">Qty</th>
          <th scope="col">Total</th>
          <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>

          <% @carts.each do |cart| %>
            <tr>
                <td scope="row"><%= cart.item.name %></td>
                <td>$<%= '%.2f' % cart.item.price %></td>
                <!-- <td>x<%= cart.item_quantity %></td> -->
                <td><%= form_with scope: :cart, :url => cart_path(cart), method: :patch, local: true  do |f| %>
                    <%# f.hidden_field :table_id, :value => session[:table] %>
                    <%# f.hidden_field :item_id, :value => cart.item.id %>
                    <% puts cart.item_quantity %>
                    <%= f.number_field :item_quantity, in: 1..10, value: cart.item_quantity, class: 'form-control form-control-sm', onchange: 'this.form.submit();' %>
                  <% end %>
                </td>
                <td><% allitem = cart.item.price * cart.item_quantity %>$<%= '%.2f' % allitem %></td>
                <td><%= link_to 'Delete Item', delete_cart_path(cart),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= form_with scope: :order, url: submit_path, local: true do |form| %>
        <p>
          <%= form.hidden_field :table_id, :value => session[:table] %>
        </p>
        <p>
          <% @carts.each do |cart| %>
          <%= form.hidden_field :item_ids,:multiple => true, :value => cart.item.id %>
          <%= form.hidden_field :item_quantities,:multiple => true, :value => cart.item_quantity %>
          <% end %>

        </p>
        <p>
          <%= form.submit "Submit order", class:"btn btn-outline-success" %>
        </p>
      <% end %>

      <%= link_to 'Back', items_path, class:"btn btn-secondary" %>
    </div>
</main>

app/views/carts/show.html.erb
<% allitem = 0 %>
<% tablesubtotal = 0 %>
<% gst = 0 %>
<% tabletotal = 0 %>


<main class="page-content">
  <div class="container-fluid">

  	<div class="row">
  		<div class="col-12">
  			<h1>Table <%= @table.id %></h1>
  		</div>
  	</div>


		<table class="table table-striped">
			<thead>
			  <tr class="row">
			  	<th class="col-1">Qty</th>
			  	<th class="col-8">Item</th>
			    <th class="col-3">Price</th>
			  </tr>
			</thead>
			<tbody>
			<% @table.orders.each do |order| %>
				<% order.items.each do |item| %>
			  <tr class="row">
		    	<% @purchases.where(order_id: order.id, item_id: item.id).each do |x| %>
		     	<td class="col-1"><%= x.item_quantity %></td>
		     	<td class="col-8"><%= item.name %></td>
		     	<td class="col-3"><% allitem = item.price * x.item_quantity %>$<%= '%.2f' % allitem %></td>
		     	<% tablesubtotal += item.price * x.item_quantity %>
		    	<% end %>
		   	</tr>
				<% end %>
			<% end %>

				<tr class="row">
			  	<td class="col-9"><b>Subtotal:</b> </td>
			  	<td class="col-3"><b>$<%= '%.2f' % tablesubtotal %></b></td>
			  </tr>
			  <tr class="row">
			  	<td class="col-9"><% gst = tablesubtotal * 0.07 %><b>GST:</b></td>
					<td class="col-3"><b>$<%= '%.2f' % gst %></b></td>
				</tr>
				<tr class="row">
					<td class="col-9"><% tabletotal = tablesubtotal + gst %><h5><b>Total:</b></h5></td>
					<td class="col-3"><h5><b> $<%= '%.2f' % tabletotal %></b></h5></td>
				</tr>
			</tbody>
		</table>


		<%= link_to 'Back', items_path, class:"btn btn-secondary" %>

app/views/items/index.html.erb
<main class="page-content">

    <div class="container-fluid">

    	<% if flash[:alert] %>
		    <div class="alert alert-success" role="alert"><%= flash[:alert] %></div>
		  <% end %>

    	<div class="row">
    		<% @items.each do |item| %>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 cards">

					<div class="card" style="width: 25rem;">
						<%= image_tag (item.picture), class:"card-img-top" %>
					  <div class="card-body">
					    <h5 class="card-title"><%= item.name %></h5>
					    <p class="card-text">$<%= '%.2f' % item.price %></p>
					    <div class="form-row">
						    <div class="col">Qty:</div>
						  </div>
						  <div class="form-row">
						    <div class="col">
						    	<%= form_with scope: :cart,  :url => add_cart_path, local: true  do |f| %>
								    	<%= f.hidden_field :table_id, :value => session[:table] %>
								    	<%= f.hidden_field :item_id, :value => item.id %>
								    	<%= f.select :item_quantity, (0..10), class:"form-control" %>
								</div>
						    <div class="col">
									    <%= f.submit "Add to Cart", class: "btn btn-outline-primary" %>
								</div>
							</div>
									<% end %>
				    </div>
				  </div>
				</div>
			<% end %>
		</div>
	</div>
</main>

<script>
	  $(".alert-success" ).fadeOut(3000);
</script>

app/views/items/show.html.erb
<main class="page-content">
  <div class="container-fluid">
  	<h1><%= @items.first.category.titleize %></h1>

  	<% if flash[:alert] %>
	    <div class="row alert alert-success" role="alert"><%= flash[:alert] %></div>
	  <% end %>

  	<div class="row">
    		<% @items.each do |item| %>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 cards">
					<div class="card" style="width: 25rem;">
						<%= image_tag (item.picture), class:"card-img-top" %>
					  <div class="card-body">
					    <h5 class="card-title"><%= item.name %></h5>
					    <p class="card-text">$<%= '%.2f' % item.price %></p>
					    <div class="form-row">
						    <div class="col">Qty:</div>
						  </div>
						  <div class="form-row">
						    <div class="col">
						    	<%= form_with scope: :cart,  :url => add_cart_path, local: true  do |f| %>
								    	<%= f.hidden_field :table_id, :value => session[:table] %>
								    	<%= f.hidden_field :item_id, :value => item.id %>
								    	<%= f.select :item_quantity, (0..10), class:"form-control" %>
								</div>
						    <div class="col">
									    <%= f.submit "Add to Cart", class: "btn btn-outline-primary" %>
								</div>
							</div>
									<% end %>
				    </div>
				  </div>
				</div>
			<% end %>
		</div>
	</div>
</main>

<script>
	  $(".alert-success" ).fadeOut(3000);
</script>