config/routes.rb
Rails.application.routes.draw do


  post '/items' => 'items#cart', as: 'add_cart'
  get '/items' => 'items#index', as: 'items'
  get '/items/:category' => 'items#show'

  get '/carts' => 'carts#index', as: 'carts'
  get '/carts/:id' => 'carts#show' , as: 'cart'
  patch '/carts/:id' => 'carts#update'
  delete '/carts/:id' => 'carts#destroy', as: 'delete_cart'


  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show' , as: 'order'
  patch '/orders/:id' => 'orders#update'
  delete '/orders/:id' => 'orders#destroy'
  post '/submit' => 'orders#submit', as: "submit"


  get '/orders/:id/items' => 'items#show' , as: 'order_items'
  delete '/orders/:id/items/:item_id' => 'items#destroy', as: 'order_item_delete'

  root "mains#index"
  get '/kitchen' => 'mains#kitchen'
  get '/table' => 'mains#table', as: "table"
  get '/getorders' => 'mains#orders'
  post '/assigntable' => 'mains#assign', as: "assign"
  get '/releasetable' => 'mains#release', as: "release"
  get '/completeorders' => 'mains#complete'
  post '/destroyalltables' => 'mains#destroy', as: "destroyall"
  delete '/deletetable' => 'tables#destroy', as: "deletetable"

  devise_for :staffs
  resources :tables

  get '/reports' => 'reports#index', as: 'reports'
  get '/sales/:id' => 'sales#show' , as: 'sale'

  get '/notifications' => 'tables#notifications'
  get '/addnotifications' => 'tables#addnotification'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  # belongs_to :order
  validates :item_quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :orders
  # has_many :carts


  # has_many :items_orders
  # has_many :orders, through: :items_orders

  # has_and_belongs_to_many :orders

end

app/models/items_order.rb
class ItemsOrder < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/notification.rb
class Notification < ApplicationRecord
end

# Notification.where('created_at >= :ten_seconds_ago', :ten_seconds_ago => Time.now - 10.seconds)

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :items_orders
  has_many :items, through: :items_orders
  
  # has_and_belongs_to_many :items
  # belongs_to :table
  # belongs_to :sale
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  # belongs_to :table
  has_many :orders
  # belongs_to :report
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/table.rb
class Table < ApplicationRecord
  # belongs_to :sale
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout "items"
  def index
    @carts = Cart.where(:table_id => session[:table]).order(:id)

  end

  def show
    @table = Table.find(session[:table])
    @purchases = Purchase.all
  end

  def update
    puts "add to cart"
    p params
    # p request.query_string
    puts params[:cart][:item_quantity]
      @cart = Cart.find(params[:id])

      @cart.update(:item_quantity => (params[:cart][:item_quantity].to_i))
    puts "finish update"

    # redirect_to carts_path
    redirect_back fallback_location: carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])

    @cart.destroy

    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:table_id, :item_id, :item_quantity)
  end

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def index
    @tables = Table.all
    render json: @tables
  end
  def new
  end
  def create
    puts '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
    puts current_staff.inspect
    puts "~~~~~~~~~~~~~~~~~~~~~~~"
    @table = Table.new
    @table.save
    redirect_to '/table'
  end
  def show
    @table = Table.find(params[:id])
    @purchases = Purchase.all
  end
  def destroy
    @table = Table.find(params[:format])
    @table.destroy
    redirect_to '/table'
  end
  def addnotification
    @addnotification = Notification.new(table_id: request.query_string.to_i)
    @addnotification.save
  end
  def notifications
    @notifications = Notification.where('created_at >= :ten_seconds_ago', :ten_seconds_ago => Time.now - 10.seconds)
    Notification.where('created_at <= :ten_seconds_ago', :ten_seconds_ago => Time.now - 10.seconds).destroy_all
    render json: @notifications
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/new.html.erb
<%= form_with scope: :table, url: tables_path, local: true do |form| %>
  <p>
    <%= form.submit "Create Table" %>
  </p>
<% end %>

app/views/tables/show.html.erb
<% if staff_signed_in? %>
<div class="container">

	<div class="row">
		<div class="col-12 text-center">
			<h1>Table <%= @table.id %></h1>
		</div>
	</div>


	<div class="row">
			<% if @table.active_status %>

			<table class="table">
			  <thead class="thead-dark">
			    <tr>
			      <th scope="col">Item</th>
			      <th scope="col">Quantity</th>
			      <th scope="col">Order Time</th>
			      <th scope="col">Status</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% @table.orders.each do |order| %>
			  		<% order.items.each do |item| %>
					    <tr>
					      <td><%= item.name %></td>
					      <% @purchases.where(order_id: order.id, item_id: item.id).each do |x| %>
					      <td>x<%= x.item_quantity %></td>
					      <% end %>
					      <td><%= order.created_at.strftime("%I:%M%p") %></td>
					      <% if order.completed %>
					      <td><span class="badge badge-pill badge-success">Completed</span></td>
					      <% else %>
					      <td><span class="badge badge-pill badge-danger">Pending</span></td>
					      <% end %>
					    </tr>
					  <% end %>
					<% end %>

			  </tbody>
			</table>

	</div>

	<div class="row">
		<div class="col-12 text-center">
			<%= button_to 'Access Table',{:controller => "mains", :action => "assign", :table_id => @table}, method: :post, :class => "btn btn-primary btn-sm" %>
			<%= button_to 'Settle Table',release_path(@table), method: :get, :class => "btn btn-success btn-sm" %>
		</div>
	</div>

	<% else %>


		<div class="col-6 text-center">
			<%= button_to 'Assign Table',{:controller => "mains", :action => "assign", :table_id => @table}, method: :post, :class => "btn btn-success btn-sm" %>
		</div>

		<div class="col-6 text-center">
			<%= button_to 'Delete Table' ,deletetable_path(@table), method: :delete, :class => "btn btn-danger btn-sm" %>
		</div>
	</div>




	<% end %>

</div>
<% end %>