config/routes.rb
Rails.application.routes.draw do


  post '/items' => 'items#cart', as: 'add_cart'
  get '/items' => 'items#index', as: 'items'
  get '/items/:category' => 'items#show'

  get '/carts' => 'carts#index', as: 'carts'
  get '/carts/:id' => 'carts#show' , as: 'cart'
  patch '/carts/:id' => 'carts#update'
  delete '/carts/:id' => 'carts#destroy', as: 'delete_cart'


  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show' , as: 'order'
  patch '/orders/:id' => 'orders#update'
  delete '/orders/:id' => 'orders#destroy'
  post '/submit' => 'orders#submit', as: "submit"


  get '/orders/:id/items' => 'items#show' , as: 'order_items'
  delete '/orders/:id/items/:item_id' => 'items#destroy', as: 'order_item_delete'

  root "mains#index"
  get '/kitchen' => 'mains#kitchen'
  get '/table' => 'mains#table', as: "table"
  get '/getorders' => 'mains#orders'
  post '/assigntable' => 'mains#assign', as: "assign"
  get '/releasetable' => 'mains#release', as: "release"
  get '/completeorders' => 'mains#complete'
  post '/destroyalltables' => 'mains#destroy', as: "destroyall"
  delete '/deletetable' => 'tables#destroy', as: "deletetable"

  devise_for :staffs
  resources :tables

  get '/reports' => 'reports#index', as: 'reports'
  get '/sales/:id' => 'sales#show' , as: 'sale'

  get '/notifications' => 'tables#notifications'
  get '/addnotifications' => 'tables#addnotification'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  # belongs_to :order
  validates :item_quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :orders
  # has_many :carts


  # has_many :items_orders
  # has_many :orders, through: :items_orders

  # has_and_belongs_to_many :orders

end

app/models/items_order.rb
class ItemsOrder < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/notification.rb
class Notification < ApplicationRecord
end

# Notification.where('created_at >= :ten_seconds_ago', :ten_seconds_ago => Time.now - 10.seconds)

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :items_orders
  has_many :items, through: :items_orders
  
  # has_and_belongs_to_many :items
  # belongs_to :table
  # belongs_to :sale
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  # belongs_to :table
  has_many :orders
  # belongs_to :report
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/table.rb
class Table < ApplicationRecord
  # belongs_to :sale
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout "items"
  def index
    @carts = Cart.where(:table_id => session[:table]).order(:id)

  end

  def show
    @table = Table.find(session[:table])
    @purchases = Purchase.all
  end

  def update
    puts "add to cart"
    p params
    # p request.query_string
    puts params[:cart][:item_quantity]
      @cart = Cart.find(params[:id])

      @cart.update(:item_quantity => (params[:cart][:item_quantity].to_i))
    puts "finish update"

    # redirect_to carts_path
    redirect_back fallback_location: carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])

    @cart.destroy

    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:table_id, :item_id, :item_quantity)
  end

end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  # before_action :set_cache_buster
  before_action :authenticate_staff!, :except => [:index ]

  def index
    puts '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
    puts current_staff.inspect
  end
  def kitchen
    @orders = Order.where(completed: nil)
    @purchases = Purchase.all
  end
  def orders
    puts "working here~"
    @orders = Order.all
    puts @orders.inspect
    render json: @orders
  end
  def complete
    order = Order.find(request.query_string)
    order.completed = true
    order.save
  end
  def table
    @tables = Table.all
  end
  def assign
    reset_session
    @table = Table.find(params[:table_id])
    @table.active_status = "true"
    @table.save
    session[:table] = params[:table_id]
    redirect_to items_path
  end
  def release
    @table = Table.find(params[:format])
    @table.active_status = ""
    @sales = Sale.new
    @sales.save
    orders = Order.where(table_id:params[:format])
    orders.each do |order|
      order.sales_id = @sales.id
      order.table_id = nil
      order.save
    end
    @table.save
    redirect_to @table
  end
  def destroy
    reset = "ALTER SEQUENCE tables_id_seq RESTART WITH 1"
    @tables = Table.all
    @tables.destroy_all
    ActiveRecord::Base.connection.execute(reset)
    redirect_to '/table'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/mains/index.html.erb
<section class="bgimage">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h5><%= image_tag image_path ("logo.png") %>YumYum</h5>
        <p class="index-page-text">The Best All-in-One Restaurant Orders Management App</p>
      </div>
    </div>
  </div>
</section>

app/views/mains/kitchen.html.erb
<% if staff_signed_in? %>

<div class="container">
	<div class="row row-buffer">
		<% @orders.each do|order| %>
		<div class="col-6">

			<div class="card border-primary mb-3" style="max-width: 20rem;">
			  <div class="card-header">Table <%= order.table_id %></div>
			  <div class="card-body">
			    <h4 class="card-title">Order No: <%= order.id %></h4>
			    <ul class="list-group">
			    	<% order.items.each do|item| %>
					  <li class="list-group-item d-flex justify-content-between align-items-center">
					    <%= item.name %>
					    <% @purchases.where(order_id: order.id, item_id: item.id).each do |x| %>
					    <span class="badge badge-primary badge-pill">x<%= x.item_quantity %></span>
					    <% end %>
					  </li>
					  <% end %>
					</ul>
			  </div>
			  <div class="modal-footer">
			  	<%= button_tag "Complete", :onclick => "completeOrder()", :id => order.id, :class => "btn btn-primary btn-sm" %>
      	</div>
			</div>
		</div>
		<% end %>
	</div>

	<div class="row">
		<div class="col-12 text-center">
			<a class="btn btn-primary btn-sm" href=<%=root_path%>>Back to main</a>
		</div>
	</div>

</div>

<% end %>






<script>
  window.onload = function(){
    setInterval(function(){

      window.location.reload()
    },3000)
  }
  function completeOrder(){
    Rails.ajax({
      url: "/completeorders",
      type: "get",
      data: event.target.id,
      success: function(data) {},
      error: function(data) {}
    })
  }
</script>

app/views/mains/table.html.erb
<% if staff_signed_in? %>

<div class="container">

	<div class="row">
		<div class="col-12 text-center">
			<%= form_with scope: :table, url: tables_path, local: true do |form| %>
		  	<p><%= form.submit "Add New Table", :class => "btn btn-sm btn-success" %></p>
			<% end %>
		</div>
	</div>

	<div class="row">
		<% @tables.each do|table| %>
		<div class="col-3">

				<a class="table-card" href=/tables/<%= table.id.to_s %>>

					<% if table.active_status? %>

						<div class="card text-white bg-danger mb-3 table-cards" id=<%= table.id%> style="max-width: 20rem;">
						  <div class="card-header">
						  	<h4>Table <%= table.id%></h4>
						  </div>
						  <div class="card-body text-center">
						    <h5 class="card-title">Status</h5>
						    <p class="card-text">Unavailable</p>
						  </div>
						</div>

					<% else %>

						<div class="card text-white bg-success mb-3 table-cards" id=<%= table.id%> style="max-width: 20rem;">
						  <div class="card-header">
						  	<h4>Table <%= table.id%></h4>
						  </div>
						  <div class="card-body text-center">
						    <h5 class="card-title">Status</h5>
						    <p class="card-text">Available</p>
						  </div>
						</div>

					<% end %>

				</a>

		</div>
		<% end %>

	</div>

	<div class="row">
		<div class="col-12 text-center">
			<%= form_with scope: :table, url: destroyall_path, local: true do |form| %>
		  	<p><%= form.submit "Clear All Tables", :class => "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' } %></p>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-12 text-center">
			<%= button_to 'Back to main', root_path, method: :get, :class => "btn btn-secondary btn-sm" %>
		</div>
	</div>

</div>

<% end %>



<script>
  window.onload = function(){
    setInterval(function(){
			Rails.ajax({
			  url: "/notifications",
			  type: "get",
			  data: "",
			  success: function(data) {
					document.querySelectorAll(".table-cards").forEach ((obj)=>{
						obj.classList.remove("blink_me")
					})
					data.forEach((obj)=>{
						var table = document.getElementById(obj.table_id)
						table.classList.add("blink_me");
					})
				},
			  error: function(data) {}
			})
			// Notification.where('created_at >= :ten_seconds_ago', :ten_seconds_ago => Time.now - 10.seconds)
      // window.location.reload()
    },3000)
  }
</script>