config/routes.rb
Rails.application.routes.draw do


  post '/items' => 'items#cart', as: 'add_cart'
  get '/items' => 'items#index', as: 'items'
  get '/items/:category' => 'items#show'

  get '/carts' => 'carts#index', as: 'carts'
  get '/carts/:id' => 'carts#show' , as: 'cart'
  patch '/carts/:id' => 'carts#update'
  delete '/carts/:id' => 'carts#destroy', as: 'delete_cart'


  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show' , as: 'order'
  patch '/orders/:id' => 'orders#update'
  delete '/orders/:id' => 'orders#destroy'
  post '/submit' => 'orders#submit', as: "submit"


  get '/orders/:id/items' => 'items#show' , as: 'order_items'
  delete '/orders/:id/items/:item_id' => 'items#destroy', as: 'order_item_delete'

  root "mains#index"
  get '/kitchen' => 'mains#kitchen'
  get '/table' => 'mains#table', as: "table"
  get '/getorders' => 'mains#orders'
  post '/assigntable' => 'mains#assign', as: "assign"
  get '/releasetable' => 'mains#release', as: "release"
  get '/completeorders' => 'mains#complete'
  post '/destroyalltables' => 'mains#destroy', as: "destroyall"
  delete '/deletetable' => 'tables#destroy', as: "deletetable"

  devise_for :staffs
  resources :tables

  get '/reports' => 'reports#index', as: 'reports'
  get '/sales/:id' => 'sales#show' , as: 'sale'

  get '/notifications' => 'tables#notifications'
  get '/addnotifications' => 'tables#addnotification'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  # belongs_to :order
  validates :item_quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :orders
  # has_many :carts


  # has_many :items_orders
  # has_many :orders, through: :items_orders

  # has_and_belongs_to_many :orders

end

app/models/items_order.rb
class ItemsOrder < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/notification.rb
class Notification < ApplicationRecord
end

# Notification.where('created_at >= :ten_seconds_ago', :ten_seconds_ago => Time.now - 10.seconds)

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :items_orders
  has_many :items, through: :items_orders
  
  # has_and_belongs_to_many :items
  # belongs_to :table
  # belongs_to :sale
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  # belongs_to :table
  has_many :orders
  # belongs_to :report
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/table.rb
class Table < ApplicationRecord
  # belongs_to :sale
  has_many :orders
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<nav class="navbar nav-tabs navbar-dark bg-dark justify-content-between flex-nowrap flex-row">

		        <a href="/" class="navbar-brand float-left"><%= image_tag image_url('taco.png'), :class => "nav-logo"  %>GA Cafe</a>
            <% if staff_signed_in? %>

		        <a href='/kitchen' class="nav-item nav-link nav-text"><%= image_tag image_url('kitchen-icon.png'), :class => "nav-icon"%>Kitchen Orders</a>
		        <a href='/table' class="nav-item nav-link nav-text"><%= image_tag image_url('table-icon.png'), :class => "nav-icon"%>Tables</a>
		        <a href="/reports" class="nav-item nav-link nav-text"><%= image_tag image_url('report-icon.png'), :class => "nav-icon"%>Reports</a>

            <% end %>

		        <ul class="nav navbar-nav flex-row float-right">
		        	<% if staff_session %>

								<li class="staff-name"><%= current_staff.email %></li>
					      <li><%= button_to "Logout", destroy_staff_session_path, method: :delete, :class => "btn btn-secondary btn-sm"%></li>
							<% else %>
		            <li class="nav-item"><a class="btn btn-secondary btn-sm" href=<%= new_staff_session_path%>>Staff Login</a></li>
		          <% end %>
		        </ul>
		</nav>


    <%= yield %>
    
  </body>
</html>

app/views/layouts/items.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  </head>

  <body>

		<div class="page-wrapper chiller-theme toggled">
		  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
		    <i class="fas fa-bars"></i>
		  </a>
		  <nav id="sidebar" class="sidebar-wrapper">
		    <div class="sidebar-content">
		      <div class="sidebar-brand">
		        <a><button onclick=assistance(<%= session[:table] %>) id="assistance" class="btn btn-primary btn-sm"><%= image_tag image_url('alarm.png'), :class => "menu-icon"%>Call for assistance </button></a>
		        <div id="close-sidebar">
		          <i class="fas fa-times"></i>
		        </div>
		      </div>

		      <div class="sidebar-header">
		      		<div class="row">
		      			<div class="col-5">
		      				<a href="/carts" class="menu-nav-text"><button type="button" class="btn btn-primary cart-button"><%= image_tag image_url('shopping-cart.png'), :class => "menu-icon"%>Cart</button></a>
		      			</div>

		      			<div class="col-7">
		      				<button type="button" class="btn btn-primary bill-button"><%= image_tag image_url('bill.png'), :class => "menu-icon"%>
		      				<%= link_to "View Bill", "/carts/#{session[:table]}", class: "menu-nav-text" %>
		      				</button>
		      			</div>
		      		</div>
		      </div>
		      <!-- sidebar-header  -->

		      <div class="sidebar-search">
		        <div>
		          <div class="input-group">
		            <input type="text" class="form-control search-menu" placeholder="Search...">
		            <div class="input-group-append">
		              <span class="input-group-text">
		                <i class="fa fa-search" aria-hidden="true"></i>
		              </span>
		            </div>
		          </div>
		        </div>
		      </div>
		      <!-- sidebar-search  -->

		      <div class="sidebar-menu">
		        <ul>
		          <li class="header-menu">
		            <span>Browse By</span>
		          </li>
		          <li>
		            <a href='/items'>
		            	<%= image_tag image_path('kitchen-icon.png')%>
		              <span class="menu-nav-text">All Items</span>
		            </a>
		          </li>
		          <li>
		            <a href='/items/starter'>
		              <%= image_tag image_path('salad.png')%>
		              <span class="menu-nav-text">Starters</span>
		              <!-- <span class="badge badge-pill badge-primary">Beta</span> -->
		            </a>
		          </li>
		          <li>
		            <a href='/items/mains'>
		              <%= image_tag image_path('meat.png')%>
		              <span class="menu-nav-text">Mains</span>
		            </a>
		          </li>
		          <li>
		            <a href='/items/sides'>
		              <%= image_tag image_path('burger.png')%>
		              <span class="menu-nav-text">Sides</span>
		            </a>
		          </li>
		          <li>
		            <a href='/items/desserts'>
		              <%= image_tag image_path('cake.png')%>
		              <span class="menu-nav-text">Desserts</span>
		            </a>
		          </li>
		          <li>
		            <a href='/items/drinks'>
		            	<%= image_tag image_path('pint.png')%>
		              <span class="menu-nav-text">Beverages</span>
		            </a>
		          </li>
		        </ul>
		      </div>
		      <!-- sidebar-menu  -->
		    </div>
		    <!-- sidebar-content  -->

		    <div class="sidebar-footer">

		    </div>
		  </nav>





    <%= yield %>

  </body>
</html>


<script>
  function assistance(id){

    Rails.ajax({
      url: "/addnotifications",
      type: "get",
      data: id,
      dataType: 'json',
      success: function(data) {},
      error: function(data) {}
    })
  }
</script>




<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between flex-nowrap flex-row">
  		<a href="/items" class="navbar-brand">Res Logo</a>


		    	<ul class="navbar-nav mr-auto text-center">
		    		<li class="nav-item">
		        	<a class="nav-link" href='/items/starter'>Starters</a>
		        </li>
		        <li class="nav-item">
		        	<a class="nav-link" href='/items/mains'>Mains</a>
		      	</li>
		      	<li class="nav-item">
			        <a class="nav-link" href="/items/desserts">Desserts</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="/items/sides">Sides</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="/items/drinks">Drinks</a>
			      </li>
            <li class="nav-item">
              <button onclick=assistance(<%= session[:table] %>) id="assistance" class="nav-link"> Call for assistance </button>
			      </li>
		      </ul>
		      <ul class="navbar-nav my-2 my-lg-0 flex-row float-right">
	            <li class="nav-item mr-sm-2"><a class="nav-link pr-3" href="/carts">Cart</a></li>
	            <li class="nav-item my-2 my-sm-0"><%= link_to "All Orders", "/carts/#{session[:table]}", class: "nav-link pr-3" %></li>
	        </ul>

		</nav> -->





		<!-- under div sidebar header -->
		<!-- <div class="user-pic">
		          <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
		            alt="User picture">
		        </div>
		        <div class="user-info">
		          <span class="user-name">Jhon
		            <strong>Smith</strong>
		          </span>
		          <span class="user-role">Administrator</span>
		          <span class="user-status">
		            <i class="fa fa-circle"></i>
		            <span>Online</span>
		          </span>
		        </div> -->